# DigitalOcean App Platform Specification
# Documentation: https://docs.digitalocean.com/products/app-platform/reference/app-spec/

name: jamhr

# Region - Choose the closest to Jamaica for lower latency
region: nyc

# Services
services:
  - name: web
    # Use Dockerfile for custom build (handles all npm/composer steps internally)
    dockerfile_path: Dockerfile

    github:
      repo: sirsmithdev/JAMHR
      branch: main
      deploy_on_push: true

    # HTTP configuration
    http_port: 8080

    # Instance configuration
    instance_count: 1
    instance_size_slug: professional-xs

    # Environment variables
    envs:
      - key: APP_NAME
        value: "JamHR"
      - key: APP_ENV
        value: "production"
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: "${APP_URL}"
        type: GENERAL
      - key: APP_KEY
        value: "${APP_KEY}"
        type: SECRET

      # Database - Use DigitalOcean Managed Database
      - key: DB_CONNECTION
        value: "pgsql"
      - key: DATABASE_URL
        scope: RUN_TIME
        value: "${db.DATABASE_URL}"

      # Session & Cache - Use file driver for simplicity (no DB dependency on boot)
      - key: SESSION_DRIVER
        value: "file"
      - key: CACHE_STORE
        value: "file"
      - key: QUEUE_CONNECTION
        value: "sync"

      # Logging
      - key: LOG_CHANNEL
        value: "stderr"
      - key: LOG_LEVEL
        value: "error"

      # Mail configuration (set these in App Platform dashboard)
      - key: MAIL_MAILER
        value: "smtp"
      - key: MAIL_HOST
        value: "${MAIL_HOST}"
        type: GENERAL
      - key: MAIL_PORT
        value: "${MAIL_PORT}"
        type: GENERAL
      - key: MAIL_USERNAME
        value: "${MAIL_USERNAME}"
        type: SECRET
      - key: MAIL_PASSWORD
        value: "${MAIL_PASSWORD}"
        type: SECRET
      - key: MAIL_FROM_ADDRESS
        value: "${MAIL_FROM_ADDRESS}"
        type: GENERAL
      - key: MAIL_FROM_NAME
        value: "JamHR"

# Database
databases:
  - name: db
    engine: PG
    version: "16"
    size: db-s-1vcpu-1gb
    num_nodes: 1

# Jobs (one-off commands like migrations)
jobs:
  - name: migrate
    kind: PRE_DEPLOY
    dockerfile_path: Dockerfile
    github:
      repo: sirsmithdev/JAMHR
      branch: main
    run_command: php artisan migrate --force
    envs:
      - key: APP_ENV
        value: "production"
      - key: APP_KEY
        value: "${APP_KEY}"
        type: SECRET
      - key: DATABASE_URL
        scope: RUN_TIME
        value: "${db.DATABASE_URL}"
      - key: DB_CONNECTION
        value: "pgsql"
