# DigitalOcean App Platform Specification
# Documentation: https://docs.digitalocean.com/products/app-platform/reference/app-spec/

name: jamhr

# Region - Choose the closest to Jamaica for lower latency
region: nyc

# Services
services:
  - name: web
    # Use Dockerfile for custom build (handles all npm/composer steps internally)
    dockerfile_path: Dockerfile

    github:
      repo: sirsmithdev/JAMHR
      branch: main
      deploy_on_push: true

    # HTTP configuration
    http_port: 8080

    # Instance configuration
    instance_count: 1
    instance_size_slug: professional-xs

    # Environment variables
    envs:
      - key: APP_NAME
        value: "JamHR"
      - key: APP_ENV
        value: "production"
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: "https://humanhr-app-jjlum.ondigitalocean.app"
      - key: ASSET_URL
        value: "https://humanhr-app-jjlum.ondigitalocean.app"
      - key: APP_KEY
        value: "base64:1ZvKiCkxZPNVYpbyPkwErLL/e4qPmfKGkLgwwGJkJZw="

      # Database - PostgreSQL 17 (DigitalOcean Managed Database)
      # Set these values in App Platform dashboard or use component binding
      - key: DB_CONNECTION
        value: "pgsql"
      - key: DB_HOST
        value: "app-b23dc1dd-f9e4-43ad-ba29-7f9201637b0a-do-user-30141255-0.e.db.ondigitalocean.com"
      - key: DB_PORT
        value: "25060"
      - key: DB_DATABASE
        value: "dev-db-447484"
      - key: DB_USERNAME
        value: "dev-db-447484"
      - key: DB_PASSWORD
        type: SECRET
        scope: RUN_AND_BUILD_TIME
      - key: DB_SSLMODE
        value: "require"

      # Session & Cache - Use file driver for simplicity (no DB dependency on boot)
      - key: SESSION_DRIVER
        value: "file"
      - key: CACHE_STORE
        value: "file"
      - key: QUEUE_CONNECTION
        value: "sync"

      # Logging
      - key: LOG_CHANNEL
        value: "stderr"
      - key: LOG_LEVEL
        value: "error"

      # Mail configuration (set these in App Platform dashboard)
      - key: MAIL_MAILER
        value: "smtp"
      - key: MAIL_HOST
        value: "${MAIL_HOST}"
        type: GENERAL
      - key: MAIL_PORT
        value: "${MAIL_PORT}"
        type: GENERAL
      - key: MAIL_USERNAME
        value: "${MAIL_USERNAME}"
        type: SECRET
      - key: MAIL_PASSWORD
        value: "${MAIL_PASSWORD}"
        type: SECRET
      - key: MAIL_FROM_ADDRESS
        value: "${MAIL_FROM_ADDRESS}"
        type: GENERAL
      - key: MAIL_FROM_NAME
        value: "JamHR"
